[Input]
InputFile = filteredMC.root
TreeName  = Event

[Output]
OutputFile = LikelihoodReco.root

[Likelihood]

#Time likelihood parameters

SigmaT   = 2.0
NWater   = 1.33
BetaMuon = 1.0


# Charge likelihood parameters

FixDirection = false
ChargeWeight  = 0.1
AttLength     = 20.0
MinExpectedPE = 1.0e-9

# -----------------------------
# Hit selection
# -----------------------------
MinPE   = 30.0
MinTime = 0.0
MaxTime = 2000.0

# PMT positions already in meter ise 1.0 kalsin
PMTPositionScale = 1.0

# Minimum PMT hit sayisi
MinHits = 20
