[input]
rootFile = /home/mutu/Desktop/RTE/data/R5/R5.root
mrdFile  = ./MRDInfo.txt
useMC     = false
[output]
rootFile = ./CCFilteredR5.root
writeMode = annotated

[cuts]
requireLAPPD            = true

# Quality cuts
beamOK                  = true
brfWindow               = true
missingPPSTick          = true
ppsIntervalSec = 5
#Physics cuts
pairedEvent             = true
promptPMTCluster        = true
highQualityPMTCluster   = true
mrdTrackReconstructed   = true
mrdRecoTrack            = false
tankMRDCoinc            = true
muonTopology            = false
noVeto                  = true

[cutValues]
promptWindowMax  = 2000.0
chargeBalanceMax = 0.2

mrdTimeWindow  = 30.0
mrdMinSideHits = 2
mrdMinTopHits  = 2

# for muonTopology cut 
lappdNeighborPMTIDs = 462,428,406,412
lappdNeighborPMTPEThreshold = 5.0 

#for brfWindow cut
brfMin = 5.0
brfMax = 30.0
