[input]
rootFile  = /home/mutu/Desktop/RTE/mcData/all0-7.root
mrdFile   = ./MRDInfo.txt
useMC     = true

[output]
rootFile = filteredMC.root
writeMode = filtered

[cuts]
trueCC = true
requireLAPPD = false
pairedEvent = true
promptPMTCluster = true
highQualityPMTCluster = true
mrdTrackReconstructed = true
mrdRecoTrack          = false
mrdSide               = false
mrdThrough            = false
mrdStop               = false
tankMRDCoinc = true
muonTopology = false
noVeto = false

[cutValues]
promptWindowMax = 2000.0
chargeBalanceMax = 0.2
mrdTimeWindow = 30.0
mrdMinSideHits = 2
mrdMinTopHits = 2
brfMin = 5.0
brfMax = 30.0

# for muonTopology cut 
lappdNeighborPMTIDs = 462,428,406,412
lappdNeighborPMTPEThreshold = 5.0 
